const CONFIG = {
  github: {
    username: 'anjan-budige',
  },
  base: '/devprofile/',
  projects: {
    github: {
      display: true,
      header: 'GitHub Projects',
      mode: 'manual',
      manual: {
        projects: [
          'anjan-budige/Skillup-Docker',
          'anjan-budige/song-finder-react',
          'anjan-budige/student-details',
          'anjan-budige/AI-imagegen',
          'anjan-budige/Trafficflow-Analysis',
          'anjan-budige/aichatbot-python',
        ],
      },
      automatic: {
        sortBy: 'stars',
        limit: 8,
        exclude: {
          forks: false,
          projects: [],
        },
      },
    },
    external: {
      header: 'My Projects',
      projects: [],
    },
  },
  seo: {
    title: 'Portfolio of Anjani Kumar Budige',
    description:
      'Passionate Full Stack MERN Developer with expertise in C, Java, Python, and DevOps. Experienced in building scalable applications and smart solutions.',
    imageURL: '',
  },
  social: {
    linkedin: 'anjani-kumar-budige',
    x: '',
    mastodon: '',
    researchGate: '',
    facebook: '',
    instagram: '',
    reddit: '',
    threads: '',
    youtube: '',
    udemy: '',
    dribbble: '',
    behance: '',
    medium: '',
    dev: '',
    stackoverflow: '',
    discord: '',
    telegram: '',
    website: '',
    phone: '+91 9989086740',
    email: 'anjanbudige@gmail.com',
  },
  resume: {
    fileUrl:
      'https://drive.google.com/file/d/1VVVqrHtoPChKR00uyYjXwnz4mekGLemc/view?usp=sharing', // Replace with actual hosted URL when deployed
  },
  skills: [
    'HTML',
    'CSS',
    'JavaScript',
    'React.js',
    'Node.js',
    'Express.js',
    'MongoDB',
    'Next.js',
    'PHP',
    'MySQL',
    'Python',
    'Java',
    'C',
    'Linux',
    'GitHub',
    'WordPress',
    'SEO',
    'Google Cloud Platform',
    'Microsoft Azure',
    'Amazon Web Services',
  ],
  experiences: [
    {
      company: 'NIT Trichy',
      position: 'Research Intern',
      from: 'June 2024',
      to: 'July 2024',
      companyLink: 'https://www.nitt.edu',
    },
  ],
  certifications: [
    {
      name: 'Genzeon Genzverse Hackathon',
      body: 'Hackathon (3 days)',
      year: 'Aug 2024',
      link: '',
    },
    {
      name: 'NIT Trichy Summer Internship',
      body: 'Internship (1 Month)',
      year: 'July 2024',
      link: '',
    },
    {
      name: 'CISCO Virtual Internship Program',
      body: 'Internship (2 Months), AICTE',
      year: 'June 2023',
      link: '',
    },
    {
      name: 'IBM SkillsBuild AI/ML Internship',
      body: 'Internship (1 Month), AICTE',
      year: 'May 2023',
      link: '',
    },
  ],
  educations: [
    {
      institution: 'Kakatiya Institute of Technology & Science',
      degree: 'B.Tech in Computer Science',
      from: '2022',
      to: '2026',
    },
    {
      institution: 'Telangana State Model School',
      degree: 'Intermediate (MPC)',
      from: '2015',
      to: '2022',
    },
  ],
  publications: [],
  blog: {
    source: '',
    username: '',
    limit: 2,
  },
  googleAnalytics: {
    id: '',
  },
  hotjar: {
    id: '',
    snippetVersion: 6,
  },
  themeConfig: {
    defaultTheme: 'lofi',
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'caramellatte',
      'abyss',
      'silk',
      'procyon',
    ],
  },
  footer: `Made by <a 
      class="text-primary" href="https://github.com/anjan-budige"
      target="_blank"
      rel="noreferrer"
    >Anjan Budige</a> with ❤️`,
  enablePWA: true,
};

export default CONFIG;
